#!/usr/bin/env python

import rospy
from std_msgs.msg import String

def send_password():
    rospy.init_node('send_password', anonymous=True)
    pub = rospy.Publisher('password_topic', String, queue_size=10)
    rate = rospy.Rate(1)  # 1 message per second

    while not rospy.is_shutdown():
        password = input("Enter the password: ")
        pub.publish(password)
        rate.sleep()

if __name__ == '__main__':
    try:
        send_password()
    except rospy.ROSInterruptException:
        pass
